## import nord theme
import: ~/.config/alacritty/nord.toml

## remove the need for close and reopen
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 50.0

[font.bold]
family = "Hack Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Medium Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Medium"

[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.8

[window.padding]
x = 25
y = 20
