import: [~/.config/alacritty/nord.toml]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window.padding]
x = 25
y = 20

[font]
size = 20.0

[font.bold]
family = "Hack Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Medium Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Medium"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
